// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​a​r​t​i​c​l​e
	 */
	particle: string
	/**
	 * F​l​a​m​e
	 */
	flame: string
	/**
	 * R​i​f​t
	 */
	rift: string
	/**
	 * M​a​g​i​c
	 */
	magic: string
	/**
	 * F​i​r​e​w​o​r​k
	 */
	firework: string
	/**
	 * B​u​t​t​e​r​f​l​y
	 */
	butterfly: string
	/**
	 * P​i​k​a​c​h​u
	 */
	pikachu: string
	/**
	 * N​y​a​n​ ​P​a​n​d​a
	 */
	nyan: string
	/**
	 * L​i​g​h​t​n​i​n​g
	 */
	lightning: string
	/**
	 * S​p​a​r​k​l​e
	 */
	sparkle: string
	settings: {
		screenShaker: {
			/**
			 * S​c​r​e​e​n​ ​s​h​a​k​e​r
			 */
			enable: string
		}
		combo: {
			/**
			 * C​o​m​b​o​!
			 */
			enable: string
		}
		cursorExplosion: {
			/**
			 * C​u​r​s​o​r​ ​e​x​p​l​o​s​i​o​n
			 */
			enable: string
			/**
			 * P​r​e​s​e​t​ ​e​f​f​e​c​t
			 */
			effect: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Particle
	 */
	particle: () => LocalizedString
	/**
	 * Flame
	 */
	flame: () => LocalizedString
	/**
	 * Rift
	 */
	rift: () => LocalizedString
	/**
	 * Magic
	 */
	magic: () => LocalizedString
	/**
	 * Firework
	 */
	firework: () => LocalizedString
	/**
	 * Butterfly
	 */
	butterfly: () => LocalizedString
	/**
	 * Pikachu
	 */
	pikachu: () => LocalizedString
	/**
	 * Nyan Panda
	 */
	nyan: () => LocalizedString
	/**
	 * Lightning
	 */
	lightning: () => LocalizedString
	/**
	 * Sparkle
	 */
	sparkle: () => LocalizedString
	settings: {
		screenShaker: {
			/**
			 * Screen shaker
			 */
			enable: () => LocalizedString
		}
		combo: {
			/**
			 * Combo!
			 */
			enable: () => LocalizedString
		}
		cursorExplosion: {
			/**
			 * Cursor explosion
			 */
			enable: () => LocalizedString
			/**
			 * Preset effect
			 */
			effect: () => LocalizedString
		}
	}
}

export type Formatters = {}
